[package]
name = "step_3_6"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
serde_yaml = "0.8.13"
toml = "0.5.6"
chrono = "0.4.15"
