[package]
name = "step_3"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
sqlx = { version = "0.3", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "uuid" ] }
dotenv = "0.15.0"
config = "0.10.1"
serde = { version = "1.0.115", features = ["derive"] }
